### ISSUE TITLE
Rename `*.txt` to `*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [jerrychong25/malaysia-map-data#255]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by jerrychong25** [comment]
Hi @FloEdelmann ,

Thanks for highlighting.

Already done the changes via https://github.com/jerrychong25/malaysia-map-data/pull/256

Feel free to loop me in if any OSM/Overpass QL changes in the future.

Cheers!

**Comment by FloEdelmann** [comment]
Thanks!

Note that since I am not a core developer or maintainer of Overpass QL, I likely won't notice all the changes to it. This renaming process is a one-time effort by me.

**Comment by jerrychong25** [comment]
> 

Noted! Thanks @FloEdelmann !
